# Generated by Django 3.2.7 on 2022-08-22 15:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('knox', '0011_authtoken_user'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logintoken',
            name='digest',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='knox.authtoken'),
            preserve_default=False,
        ),
    ]
